### ISSUE TITLE
Let's create unit tests and put `testString` there ?

### ISSUE THREAD

**Issue by wertlex** [Wolandrtf/validate-brackets#1]
Could we maybe move `testString` from here https://github.com/Wolandrtf/validate-brackets/blob/main/index.js#L1-L5 to collection of small unit tests?

[Mocha](https://github.com/mochajs/mocha) could be a nice candidate to use for testing

**Comment by Wolandrtf** [comment]
My bad, I forgot to delete test data from index file...

> Could we maybe move `testString` from here https://github.com/Wolandrtf/validate-brackets/blob/main/index.js#L1-L5 to collection of small unit tests?
> 
> [Mocha](https://github.com/mochajs/mocha) could be a nice candidate to use for testing
